services:
  - type: web
    name: spec-extractor
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PORT
        value: 5001
