services:
  - type: web
    name: spec-extractor
    env: python
    buildCommand: |
      rm -rf /opt/render/.cache/ms-playwright
      pip install -r requirements.txt
      playwright install --with-deps
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 5001
