services:
  - type: web
    name: spec-extractor
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y wget unzip curl gnupg && \
      curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list && \
      apt-get update && \
      apt-get install -y google-chrome-stable && \
      CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+') && \
      wget -O chromedriver.zip "https://chromedriver.storage.googleapis.com/$CHROME_VERSION/chromedriver_linux64.zip" && \
      unzip chromedriver.zip && \
      mv chromedriver /usr/local/bin/chromedriver && \
      chmod +x /usr/local/bin/chromedriver
    startCommand: "python app.py"
    envVars:
      - key: PORT
        value: 5001
