services:
  - type: web
    name: spec-extractor
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y wget unzip curl gnupg2 libglib2.0-0 libnss3 libgconf-2-4 libfontconfig1 libxss1 libappindicator3-1 libasound2 libatk-bridge2.0-0 libgtk-3-0 xvfb && \
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
      dpkg -i google-chrome-stable_current_amd64.deb || apt-get -fy install && \
      CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+') && \
      wget -O chromedriver.zip "https://chromedriver.storage.googleapis.com/$CHROME_VERSION/chromedriver_linux64.zip" && \
      unzip chromedriver.zip && \
      mv chromedriver /usr/local/bin/chromedriver && \
      chmod +x /usr/local/bin/chromedriver
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
